language: node_js
node_js:
  - 14
cache:
  directories:
  - node_modules
env:
  - CI=true
script:
  - npm run build-storybook
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: storybook-static # 项目打包后生成的文件的目录
  github-token: $GITHUB_TOKEN # 这里这个变量就是刚才配置 token 时填写的那个变量
  keep-history: true
  on:
    branch: main # 项目源码所在的分支